name: WelcomeMessages
version: 1.0.0
main: TStark\WelcomeMessages\Main
api: 5.0.0
author: §bT. Stark
commands:
  wmreload:
    description: Recarga la configuración del plugin.
website: §ahttps://mcpetools.surge.sh