# Welcome messages
welcome_message: "§aWelcome, {player}, to the server!"

# Messages from worlds
world_messages:
  parcelas: "§eYou are in §bPlots"
  minas: "§eYou are in §bMinas"
  pvp: "§eYou are in §bPvP"
  survival: "§eYou are in §bSurvival"

# Death messages
death_messages:
  fall: "§c{player} died from a fall."
  drowning: "§c{player} drowned."
  hunger: "§c{player} died of hunger."
  default: "§c{player} died."

# Murder Messages
kill_messages:
  default: "§c{player} was killed by {killer} using {weapon}."
